"""add_status_to_clients

Revision ID: 1380cc5353a6
Revises: 43d724dabe79
Create Date: 2025-07-28 10:50:08.819102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1380cc5353a6'
down_revision: Union[str, Sequence[str], None] = '43d724dabe79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column as nullable first
    op.add_column('clients', sa.Column('status', sa.String(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE clients SET status = 'pending' WHERE status IS NULL")
    
    # Make the column not nullable
    op.alter_column('clients', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'status')
    # ### end Alembic commands ###
