"""add_under_approval_status_and_document_reviews_table

Revision ID: 28f501bce8ed
Revises: 595bbc34b6b6
Create Date: 2025-07-28 16:02:52.357907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f501bce8ed'
down_revision: Union[str, Sequence[str], None] = '595bbc34b6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
