"""add must_reset_password to employees

Revision ID: 42bf7c9710a4
Revises: 83feeb6692d6
Create Date: 2025-07-18 15:55:00.788738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bf7c9710a4'
down_revision: Union[str, Sequence[str], None] = '83feeb6692d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('must_reset_password', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'must_reset_password')
    # ### end Alembic commands ###
