"""add_timestamps_to_clients_table

Revision ID: 43d724dabe79
Revises: a5c8111c6cc3
Create Date: 2025-07-28 10:42:35.167422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d724dabe79'
down_revision: Union[str, Sequence[str], None] = 'a5c8111c6cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('clients', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'deleted_at')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
