"""create audits table

Revision ID: 6ef084eda3ab
Revises: e0e4a7e26183
Create Date: 2025-07-21 12:55:44.447934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef084eda3ab'
down_revision: Union[str, Sequence[str], None] = 'e0e4a7e26183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audittypeenum = sa.Enum('internal', 'external', 'compliance', 'regulatory', 'financial', name='audittypeenum')
    audittypeenum.create(op.get_bind(), checkfirst=True)
    op.add_column('audits', sa.Column('lead_auditor_id', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('scope', sa.String(), nullable=True))
    op.alter_column('audits', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'audits', 'employees', ['lead_auditor_id'], ['id'])
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_code')
    )
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audittypeenum = sa.Enum('internal', 'external', 'compliance', 'regulatory', 'financial', name='audittypeenum')
    audittypeenum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_table('audits')
    # ### end Alembic commands ###
