"""Add avatar_url, signature, status to employees

Revision ID: 83feeb6692d6
Revises: 9b39e6e67f14
Create Date: 2025-07-18 14:41:10.031611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '83feeb6692d6'
down_revision: Union[str, Sequence[str], None] = '9b39e6e67f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('signature', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'signature')
    op.drop_column('employees', 'avatar_url')
    # ### end Alembic commands ###
