"""add created_at, updated_at, deleted_at columns to all tables

Revision ID: 9b294593c787
Revises: 42bf7c9710a4
Create Date: 2025-07-21 11:23:25.866702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b294593c787'
down_revision: Union[str, Sequence[str], None] = '42bf7c9710a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('login_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('login_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('login_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tokens', sa.Column('created_at_ts', sa.DateTime(), nullable=True))
    op.add_column('tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'deleted_at')
    op.drop_column('tokens', 'updated_at')
    op.drop_column('tokens', 'created_at_ts')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('login_logs', 'deleted_at')
    op.drop_column('login_logs', 'updated_at')
    op.drop_column('login_logs', 'created_at')
    op.drop_column('employees', 'deleted_at')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('departments', 'deleted_at')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    # ### end Alembic commands ###
