"""Add logout_time column to login_logs

Revision ID: 9b39e6e67f14
Revises: 4306a2644b8a
Create Date: 2025-07-18 12:53:08.460117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b39e6e67f14'
down_revision: Union[str, Sequence[str], None] = '4306a2644b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_logs', sa.Column('logout_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_logs', 'logout_time')
    # ### end Alembic commands ###
