"""add roles and departments tables and update employees

Revision ID: bb16facff366
Revises: 312a9a42aae6
Create Date: 2025-07-17 18:02:35.777222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb16facff366'
down_revision: Union[str, Sequence[str], None] = '312a9a42aae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'role_id')
    op.drop_column('employees', 'department_id')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
