"""update audit table: add lead_auditor_id, scope, type enum, nullable department_id, etc.

Revision ID: eb92eb007aea
Revises: 6ef084eda3ab
Create Date: 2025-07-21 14:54:15.964859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb92eb007aea'
down_revision: Union[str, Sequence[str], None] = '6ef084eda3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audittypeenum = sa.Enum('internal', 'external', 'compliance', 'regulatory', 'financial', name='audittypeenum')
    audittypeenum.create(op.get_bind(), checkfirst=True)
    op.add_column('audits', sa.Column('lead_auditor_id', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('scope', sa.String(), nullable=True))
    op.alter_column('audits', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audits', 'type',
               existing_type=sa.VARCHAR(),
               type_=audittypeenum,
               existing_nullable=False,
               postgresql_using="type::audittypeenum")
    op.create_foreign_key(None, 'audits', 'employees', ['lead_auditor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audits', type_='foreignkey')
    op.alter_column('audits', 'type',
               existing_type=sa.Enum('internal', 'external', 'compliance', 'regulatory', 'financial', name='audittypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('audits', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audits', 'scope')
    op.drop_column('audits', 'lead_auditor_id')
    audittypeenum = sa.Enum('internal', 'external', 'compliance', 'regulatory', 'financial', name='audittypeenum')
    audittypeenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
