"""add_under_approval_to_document_status_enum

Revision ID: f62b1e6eb486
Revises: 28f501bce8ed
Create Date: 2025-07-28 16:19:38.672606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62b1e6eb486'
down_revision: Union[str, Sequence[str], None] = '28f501bce8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'under_approval' to the documentstatusenum
    op.execute("ALTER TYPE documentstatusenum ADD VALUE 'under_approval'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values, so we can't downgrade this
    pass
    # ### end Alembic commands ###
